### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by mozhuqing** [AdneneBoumessouer/Anomaly-Detection#11]
nb_training_images_aug = args.images
AttributeError: 'Namespace' object has no attribute 'images'

**Comment by AdneneBoumessouer** [comment]
Try running the latest version of the training script on the master branch.

Command example:
python3 train.py new -d mvtec/capsule -a mvtec -b 24 -l mse

**Comment by mozhuqing** [comment]
What is the test script? Thank you

**Comment by mozhuqing** [comment]
What is the test script? There is also a mark on the picture in the original text. Is this reflected in the code? Thank you very much.

**Comment by AdneneBoumessouer** [comment]
The test script is nor yet finished. I'll update the readme file later today to describe how to use the scripts.

**Comment by mozhuqing** [comment]
Thank you very much, looking forward to your update! I'm almost a fan of you.
