### ISSUE TITLE
raise ValueError("third dimension must be 3 or 4") ValueError: third dimension must be 3 or 4

### ISSUE THREAD

**Issue by mozhuqing** [AdneneBoumessouer/Anomaly-Detection#12]
An error occurred when I ran validate.py with a script. The data set gives a graph with dimension 3. How can I fix this mistake?

**Comment by AdneneBoumessouer** [comment]
which command did you use to run the validation script exactly ?

**Comment by AdneneBoumessouer** [comment]
You maybe still running the old version of validate.py. Try pulling the new version from the master branch and try running the validation script as explained in the readme.

**Comment by mozhuqing** [comment]
That is:
"python validate.py -p saved_models/SSIM/21-02-2020_09/CAE_mvtec_b32.h5"

**Comment by AdneneBoumessouer** [comment]
Hi,
I have fixed the bug in the branch `dev2`. So you need to pull from this branch for the error not to occur during validation. I have also corrected a mistake related to the mvtec model architecture. You'll now be able to see much better reconstructions. You can check some of the latest validation results in `saved_models/MSE` and `saved_models/SSIM`, which contain an example image, its reconstruction and the resulting resmap.
