### ISSUE TITLE
Did you use the MVtec data set to do defect detection?

### ISSUE THREAD

**Issue by mozhuqing** [AdneneBoumessouer/Anomaly-Detection#5]
Did you use the MVtec data set to do defect detection? Or reappear SSIM CNN autoencoder (improving unsupervised defect segmentation

By applying structural simplicity to autoencoders and MVtec ad-a comprehensive real world dataset for unsupervised

Anomaly Detection）

**Comment by AdneneBoumessouer** [comment]
Yes I am.
